### ISSUE TITLE
关于新角色的别称

### ISSUE THREAD

**Issue by ghost** [pcrbot/gacha#12]
由于数据源的新角色数据是先添加日文原名，过几日后再追加其他别称，但自动更新只会在新角色出的时候添加一次数据的缘故，导致不手动补充的话，新角色的别称往往只有日文原名。因此认为，添加一个写入新角色后过一段时间再次检查并覆盖别称的定时任务，以及添加一个检查并覆盖别称的指令比较好。

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by var-mixer** [comment]
因为每个机器人都会有自己额外添加的一些别称，所以是会跳过已有的角色的。定时检查也不太靠谱，因为标准格式下第二个昵称才应该是日文名，而有的插件可能依赖此顺序，不如自己加（X

因为登陆服务器添加比较麻烦，所以实际上`_pcr_data.py`预留了添加角色别称的接口，我自己写的指令因为和别的部分耦合所以没有发上来，可以先自己随便写个凑合用用，晚点我有空了加个几个指令。

**Comment by ghost** [comment]
非常感谢！

**Comment by ModChino** [comment]
同，非常感谢！
