### ISSUE TITLE
近几期更新卡池后，限定角色会被保存在常驻卡池

### ISSUE THREAD

**Issue by Rcrafte22** [pcrbot/gacha#14]

**Comment by var-mixer** [comment]
更新源的问题，这个插件只是搬运更新源的数据。不过根本原因是阿B铁憨憨，限定卡池不给标记限定。先自己手动处理吧。

**Comment by kkbllt** [comment]
近期可能会尝试使用日服源对啊b服的常驻池子做限制，不要太抱有希望。
正如之前日服突然来了个双池子一样说不定会完全不管…

**Comment by kkbllt** [comment]
> _No description provided._



> 更新源的问题，这个插件只是搬运更新源的数据。不过根本原因是阿B铁憨憨，限定卡池不给标记限定。先自己手动处理吧。

目前暂时修复了限定角色进常住的问题，顺便日服双卡池的处理是两个up合一。毕竟这只是bot的模拟抽卡功能不考虑跟游戏做100%匹配。
