### ISSUE TITLE
自动更新网站的证书出问题了？

### ISSUE THREAD

**Issue by H-K-Y** [pcrbot/gacha#18]
更新报错了，提示网站证书已过期
![QQ截图20210330153133](https://user-images.githubusercontent.com/33424676/112951171-a7f13e00-916d-11eb-98b4-4e4456f8f970.png)

**Comment by H-K-Y** [comment]
![QQ截图20210330153730](https://user-images.githubusercontent.com/33424676/112951425-eb4bac80-916d-11eb-8106-2475a1db322d.png)
太秀了，正好今天过期............

**Comment by var-mixer** [comment]
看最新一次[commit](https://github.com/pcrbot/gacha/commit/345179d1e185e389d219e2ad41405c5c861612d0)，已经取消了证书验证，我这边是可以正常更新的。

**Comment by H-K-Y** [comment]
原来如此，我完全明白了.jpg
