### ISSUE TITLE
git来还是水吃时候的尺子怎么办啊大佬

### ISSUE THREAD

**Issue by rhwong** [pcrbot/gacha#6]
更新指令无效，我就重新git了一下，还是水吃池。。

**Comment by var-mixer** [comment]
请提供发送指令后的日志信息，报错信息（如有）。
以及群内执行指令后的回复结果（如有）。

**Comment by rhwong** [comment]
第一次没反馈，我发现是因为设置了hoshino的全局前缀，所以指令根本没匹配。然后又发了还是不行，最后改了路径好了、谢谢大佬回复
