### ISSUE TITLE
游骑兵系列咖啡佬的_pcr_data用的是游侠，某些卡池会找不到角色

### ISSUE THREAD

**Issue by ringoFF** [pcrbot/gacha#7]
把游骑兵替换成游侠就好了

**Comment by var-mixer** [comment]
我看了下`_pcr_data.py`的修改历史，咖啡佬在8月5日提交了一次针对角色名称的修改（[b256942](https://github.com/Ice-Cirno/HoshinoBot/commit/7cfa868ec7d6f777ab608b77743af32d34add551#diff-7cb6cbc27352fcca4672d1966d984863)），将游骑兵更换为了游侠。
我部署的时间早于此，而且之后没有针对已有数据修改。

随后我会将此说明追加到README中，感谢。
