### ISSUE TITLE
up列表与s3列表重合导致判定出错

### ISSUE THREAD

**Issue by assassingyk** [pcrbot/gacha#8]
up列表与s3列表重合导致判定出错
如题。直接从干炸里脊api获取到的卡池列表会把当期up角色也列在s3里面，但实际上s3列表中不应填写up角色，所以导致出现up数量判定错误的问题。甚至出现明明结果里有up但评语显示吃井的情况……

（例，台服卡池，爽弓up，结果有爽弓但显示吃井）
![0L%9X@ GAK4N7F74)CO@4@4](https://user-images.githubusercontent.com/55473115/92422734-ff6b9480-f1b0-11ea-82a5-6bccb9a18e41.jpg)

建议修改下update.py，在导入卡池时自动判定下，如果up出现在了s3列表里就自动剔除什么的）

**Comment by var-mixer** [comment]
现在`up`池中的角色会自动在`star3`中移除（如果有的话）
