### ISSUE TITLE
是否考虑增加自动写入花名册功能

### ISSUE THREAD

**Issue by ghost** [pcrbot/gacha#9]
目前的自动更新仅限于台B服，在日服出现新角色时控制台只会提示需要更新新ID角色的静态资源，然后因为up为空值直接替换为万圣镜华卡池。所以最终依然需要手动更新。
是否考虑利用https://api.redive.lolikon.icu/gacha/unitdata.py， 在新ID不在_pcr_data中时写入新的一行或者直接覆盖并执行重载花名册指令，从而实现新角色的自动更新。

**Comment by var-mixer** [comment]
已添加，为可选功能。
